// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN769DzqBMfmeWPEe9HU6yfnQA1qzWrJI',
    appId: '1:219424244128:web:2f785e7703f6d12075a4c5',
    messagingSenderId: '219424244128',
    projectId: 'final-project-28230',
    authDomain: 'final-project-28230.firebaseapp.com',
    storageBucket: 'final-project-28230.firebasestorage.app',
    measurementId: 'G-CM09MD9CQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHkC1p4hqpKszCj2LVUsk6At_z3DxxMP0',
    appId: '1:219424244128:android:ebf7e892a4de548475a4c5',
    messagingSenderId: '219424244128',
    projectId: 'final-project-28230',
    storageBucket: 'final-project-28230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOZYAMbZ1dcVWvLnJes2Xad1CnQKkZV38',
    appId: '1:219424244128:ios:ca9d5415b0ac5e9c75a4c5',
    messagingSenderId: '219424244128',
    projectId: 'final-project-28230',
    storageBucket: 'final-project-28230.firebasestorage.app',
    androidClientId: '219424244128-o80r903m6u49fts46pjv7if4fphk2fko.apps.googleusercontent.com',
    iosClientId: '219424244128-i0lgij400osed53upknk14779505j2hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.xspireDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOZYAMbZ1dcVWvLnJes2Xad1CnQKkZV38',
    appId: '1:219424244128:ios:ca9d5415b0ac5e9c75a4c5',
    messagingSenderId: '219424244128',
    projectId: 'final-project-28230',
    storageBucket: 'final-project-28230.firebasestorage.app',
    androidClientId: '219424244128-o80r903m6u49fts46pjv7if4fphk2fko.apps.googleusercontent.com',
    iosClientId: '219424244128-i0lgij400osed53upknk14779505j2hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.xspireDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN769DzqBMfmeWPEe9HU6yfnQA1qzWrJI',
    appId: '1:219424244128:web:e9627a63949d900a75a4c5',
    messagingSenderId: '219424244128',
    projectId: 'final-project-28230',
    authDomain: 'final-project-28230.firebaseapp.com',
    storageBucket: 'final-project-28230.firebasestorage.app',
    measurementId: 'G-NPXC3QK09E',
  );
}
